export const Actions = {
  GET_POKEMONS_LIST_REQUEST: 'GET_POKEMONS_LIST_REQUEST',
  GET_POKEMONS_LIST_SUCCESS: 'GET_POKEMONS_LIST_SUCCESS',
  GET_POKEMONS_LIST_ERROR: 'GET_POKEMONS_LIST_ERROR',
  SET_COUNT: 'SET_COUNT',
}